letter_opener_web.gemspec

Some Rails projects do not rely on Rails, like those not using ActiveRecord. We shouldn't force those projects to download unnecessary gems.

Depend on the railties gem rather than the rails one

---

lib/letter_opener_web/delivery_method.rb

Here's a fix for a tiny Ruby :warning:.

⚠️ assigned but unused variable - messages

---

README.md

Now '1.3.0' is released.
https://github.com/fgrehm/letter_opener_web/tree/v1.3.0
And to keep this version specification is hard to maintain.

Remove version lock from "Installation" section in README

---

Gemfile.lock
README.md
app/models/letter_opener_web/letter.rb
lib/letter_opener_web.rb
lib/letter_opener_web/engine.rb
spec/letter_opener_web_spec.rb
spec/models/letter_opener_web/letter_spec.rb

Resolves #57 
When changing the default location for letters, it should be sufficient to set `LetterOpenerWeb::Letter.letters_location` in an initializer (or development.rb).
However, currently the engine hard codes the path, which is not ideal
@nicolas-besnard @josisusan would either of you be able to verify that this resolves the issue?

One location def to rule them all

---

app/views/letter_opener_web/letters/index.html.erb

Currently if you mount letter_opener_web within a namespace, the URL helpers used in `letters#index` go :boom:
To try it out, update routes.rb as follows:
```ruby
Rails.application.routes.draw do
namespace :inbox do
mount LetterOpenerWeb::Engine => '/letter_opener'
end
end
```
Without this PR, going to `/inbox/letter_opener` raises. With it, 🥅

Support for Namespaced Mounting

---

lib/letter_opener_web/engine.rb

This PR does exactly the same thing as https://github.com/ryanb/letter_opener/pull/89
Please don't directly touch ActionMailer::Base class in the initializer but use ActiveSupport on_load hook as documented here: http://api.rubyonrails.org/classes/ActiveSupport/LazyLoadHooks.html

Lazy-load ActionMailer::Base to defer :action_mailer on_load hook

---

app/assets/javascripts/letter_opener_web/application.js

when I clicked on table head, the element added active class. 
I fixed to add active class only table body elements.

fix active element behaivor

---

lib/letter_opener_web/delivery_method.rb

Since a new version of `letter_opener` is released and there's a change in `LetterOpener::Message.rendered_messages` method (now we send location using `options` param) `letter_opener_web` is broken when `letter_opener_web` as delivery method is used (sorry about that). 
There's a bug report about it here https://github.com/ryanb/letter_opener/issues/147. I think it makes sense to disable Launchy using `LAUNCHY_DRY_RUN` env variable (https://github.com/copiousfreetime/launchy/blob/master/lib/launchy.rb#L15) to avoid future issues with compatibilities with `letter_opener` gem. What do you think?

Disable Launchy using ENV variable instead of completely redefining `deliver!` method.

---

lib/letter_opener_web/delivery_method.rb

When Launchy runs dry run mode, its runner will detect executable command.
Ref: https://github.com/copiousfreetime/launchy/blob/v2.4.3/lib/launchy/detect/runner.rb#L58
It makes sense for Launchy. So letter_opener_web should be avoid this error.
This PR follows up https://github.com/fgrehm/letter_opener_web/pull/73.

Disable Launchy and ignore executable command detection

---

app/controllers/letter_opener_web/letters_controller.rb

@davekaro @pseudomuto 
thank you for your feedbacks on https://github.com/fgrehm/letter_opener_web/pull/79

Add require_dependency

---

app/controllers/letter_opener_web/letters_controller.rb

Ref: https://github.com/rails/rails/pull/37599
That `require_dependency` is here to workaround a limitation in Rails's Classic autoloader ([as explained here](https://guides.rubyonrails.org/v5.1.4/autoloading_and_reloading_constants.html#when-constants-aren-t-missed-qualified-references)).
Since Rails 6, there's a new autoloader available, which doesn't have this limitation, as well as an option to not add autoloaded paths to the global `$LOAD_PATH`.
That later option breaks `latter_opener_web`.
@pseudomuto @rafaelfranca @Edouard-Chin @etiennebarrie

Avoid require_dependency if Zeitwerk is enabled

---

Gemfile
spec/spec_helper.rb

Adding codecov to keep us honest

Setup codecov report in CI

---

app/controllers/letter_opener_web/letters_controller.rb
app/models/letter_opener_web/letter.rb
spec/controllers/letter_opener_web/letters_controller_spec.rb
spec/models/letter_opener_web/letter_spec.rb

This PR ensures that when attempting to view or delete a letter, the provided `:id` is within the letters base path.

Ensure letter is within letters base path

---

config/routes.rb

This error occurred when using Rails API mode.
```
Started POST "/letter_opener/clear" for 172.18.0.1 at 2017-07-25 03:07:35 +0000
ActionController::RoutingError (No route matches [POST] "/letter_opener/clear"):
```
Plead add this routes.
```ruby
post 'clear'                 => 'letters#clear'
post ':id'                   => 'letters#destroy'
```
related. https://github.com/fgrehm/letter_opener_web/issues/42

[add]routes for rails api mode

---

app/controllers/letter_opener_web/letters_controller.rb

I installed letter_opener_web in my rails app, I found conflicting `Letter` class with my own `Letter` class.
I'd like to explicit `Letter` class's name space in `letter_opener_web`.
If there is other solutions without changing `letter_opener_web`, I'd like to choose that.

Explicit `Letter` class for avoiding name conflict

---

app/controllers/letter_opener_web/application_controller.rb

The HTML contains the anti-CSRF token in https://github.com/fgrehm/letter_opener_web/blob/feea82d0b279bfabe8e61891eecdc6098287f77e/app/views/layouts/letter_opener_web/letters.html.erb#L9 however the `protect_from_forgery` call was missing from `ApplicationController`.

Add Rails' built-in CSRF protection

---

.github/workflows/main.yml

This branch was specified as CI target in https://github.com/fgrehm/letter_opener_web/pull/114/commits/104bd2f39e3aa664e5fbfa90689fdc20aef9c77c.
However, "next" has been merged into "master" branch in https://github.com/fgrehm/letter_opener_web/pull/113.

[Refactor] Remove "next" branch from CI target

---

.rubocop_todo.yml
CHANGELOG.md
app/models/letter_opener_web/letter.rb

The count of elements is (or at least can be) different depending on the email headers - like reply-to, etc… So rather than relying on the count and stripping the last two, find the `<dt>` containing the "Attachments:" label text, and then remove it and the element following it.
Here's what it looks like with this patch applied. Note the Attachments aren't in the sidebar, but still show up in the iframe.
(This is replacing #132 which is the same change, but I deleted the remote. Yay me! Yay Git!)

Strip Attachment elements from sidebar

---

letter_opener_web.gemspec

Here's a patch that excludes files under spec directory from the gem package.
With this patch, the gem package size shrinks as follows:
```
before: 92160 bytes
after:  78336 bytes
```

Exclude spec files from gem package

---

config/routes.rb
spec/dummy/config/routes.rb

See https://github.com/rails/rails/pull/52422

Remove deprecated calls to routing mapper
